"""Initial schema - match existing DDL

Revision ID: f96dbbf2311e
Revises: 
Create Date: 2026-02-18 11:24:36.373928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96dbbf2311e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deployable', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_name'),
    sa.UniqueConstraint('sort_order'),
    schema='asset'
    )
    op.create_table('location_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name'),
    schema='asset'
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_name'),
    schema='asset'
    )
    op.create_table('operating_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('os_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_name'),
    schema='asset'
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_name'),
    schema='auth'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    schema='auth'
    )
    op.create_table('hardware_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name'),
    schema='equip'
    )
    op.create_table('software_family',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_name'),
    schema='equip'
    )
    op.create_table('software_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name'),
    schema='equip'
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['itsm.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    schema='itsm'
    )
    op.create_table('impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('impact_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impact_name'),
    sa.UniqueConstraint('sort_order'),
    schema='itsm'
    )
    op.create_table('priority',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('sla_response_hours', sa.Integer(), nullable=True),
    sa.Column('sla_resolve_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_name'),
    sa.UniqueConstraint('sort_order'),
    schema='itsm'
    )
    op.create_table('severity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('severity_name'),
    sa.UniqueConstraint('sort_order'),
    schema='itsm'
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name', 'entity_type', name='UQ_status_name_entity'),
    schema='itsm'
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='org'
    )
    with op.batch_alter_table('department', schema='org') as batch_op:
        batch_op.create_index(batch_op.f('ix_org_department_department_code'), ['department_code'], unique=True)

    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('location_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['location_type_id'], ['asset.location_type.id'], ),
    sa.ForeignKeyConstraint(['parent_location_id'], ['asset.location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name', 'parent_location_id', name='UQ_location_name_parent'),
    schema='asset'
    )
    with op.batch_alter_table('location', schema='asset') as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_location_location_type_id'), ['location_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_location_parent_location_id'), ['parent_location_id'], unique=False)

    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='UQ_role_permission_role_permission'),
    schema='auth'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entra_object_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('provisioned_by', sa.Integer(), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(), nullable=True),
    sa.Column('first_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['provisioned_by'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('entra_object_id'),
    schema='auth'
    )
    op.create_table('software',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('software_type_id', sa.Integer(), nullable=False),
    sa.Column('software_family_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('license_model', sa.String(length=20), nullable=False),
    sa.Column('license_tier', sa.String(length=50), nullable=True),
    sa.Column('cost_per_license', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['software_family_id'], ['equip.software_family.id'], ),
    sa.ForeignKeyConstraint(['software_type_id'], ['equip.software_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equip'
    )
    with op.batch_alter_table('software', schema='equip') as batch_op:
        batch_op.create_index(batch_op.f('ix_equip_software_software_family_id'), ['software_family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equip_software_software_type_id'), ['software_type_id'], unique=False)

    op.create_table('division',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('division_code', sa.String(length=50), nullable=False),
    sa.Column('division_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['org.department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='org'
    )
    with op.batch_alter_table('division', schema='org') as batch_op:
        batch_op.create_index(batch_op.f('ix_org_division_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_division_division_code'), ['division_code'], unique=True)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hardware_type_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('operating_system_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_deployed', sa.Boolean(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['asset.condition.id'], ),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['equip.hardware_type.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['asset.location.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['asset.manufacturer.id'], ),
    sa.ForeignKeyConstraint(['operating_system_id'], ['asset.operating_system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    schema='asset'
    )
    with op.batch_alter_table('asset', schema='asset') as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_asset_hardware_type_id'), ['hardware_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_asset_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_asset_manufacturer_id'), ['manufacturer_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('hr_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('records_processed', sa.Boolean(), nullable=False),
    sa.Column('records_created', sa.Boolean(), nullable=False),
    sa.Column('records_updated', sa.Boolean(), nullable=False),
    sa.Column('records_deactivated', sa.Boolean(), nullable=False),
    sa.Column('records_errors', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('user_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org.department.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['org.division.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    with op.batch_alter_table('user_scope', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_user_scope_user_id'), ['user_id'], unique=False)

    op.create_table('cost_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('total_hardware_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_software_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_table('hardware_type_cost_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hardware_type_id', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_date', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['equip.hardware_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    with op.batch_alter_table('hardware_type_cost_history', schema='budget') as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_hardware_type_cost_history_hardware_type_id'), ['hardware_type_id'], unique=False)

    op.create_table('software_cost_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_license', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_date', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['equip.software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    with op.batch_alter_table('software_cost_history', schema='budget') as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_software_cost_history_software_id'), ['software_id'], unique=False)

    op.create_table('change_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('implementer_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['itsm.category.id'], ),
    sa.ForeignKeyConstraint(['implementer_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['itsm.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itsm'
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_code', sa.String(length=50), nullable=False),
    sa.Column('position_title', sa.String(length=200), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('authorized_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['org.division.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='org'
    )
    with op.batch_alter_table('position', schema='org') as batch_op:
        batch_op.create_index(batch_op.f('ix_org_position_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_position_position_code'), ['position_code'], unique=True)

    op.create_table('authorized_count_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('authorized_count', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    with op.batch_alter_table('authorized_count_history', schema='budget') as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_authorized_count_history_position_id'), ['position_id'], unique=False)

    op.create_table('requirement_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    with op.batch_alter_table('requirement_history', schema='budget') as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_requirement_history_position_id'), ['position_id'], unique=False)

    op.create_table('position_hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('hardware_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['equip.hardware_type.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'hardware_type_id', name='UQ_position_hardware_position_type'),
    schema='equip'
    )
    with op.batch_alter_table('position_hardware', schema='equip') as batch_op:
        batch_op.create_index(batch_op.f('ix_equip_position_hardware_hardware_type_id'), ['hardware_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equip_position_hardware_position_id'), ['position_id'], unique=False)

    op.create_table('position_software',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['equip.software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'software_id', name='UQ_position_software_position_software'),
    schema='equip'
    )
    with op.batch_alter_table('position_software', schema='equip') as batch_op:
        batch_op.create_index(batch_op.f('ix_equip_position_software_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equip_position_software_software_id'), ['software_id'], unique=False)

    op.create_table('software_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org.department.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['org.division.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['equip.software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equip'
    )
    with op.batch_alter_table('software_coverage', schema='equip') as batch_op:
        batch_op.create_index(batch_op.f('ix_equip_software_coverage_software_id'), ['software_id'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['itsm.category.id'], ),
    sa.ForeignKeyConstraint(['impact_id'], ['itsm.impact.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['itsm.priority.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['itsm.severity.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['itsm.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itsm'
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['itsm.category.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['itsm.priority.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['auth.user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['itsm.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itsm'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('neogov_employee_id', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neogov_employee_id'),
    schema='org'
    )
    with op.batch_alter_table('employee', schema='org') as batch_op:
        batch_op.create_index(batch_op.f('ix_org_employee_position_id'), ['position_id'], unique=False)

    op.create_table('asset_assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=200), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['org.employee.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='asset'
    )
    with op.batch_alter_table('asset_assignment', schema='asset') as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_assignment_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_assignment', schema='asset') as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_asset_assignment_asset_id'))

    op.drop_table('asset_assignment', schema='asset')
    with op.batch_alter_table('employee', schema='org') as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_employee_position_id'))

    op.drop_table('employee', schema='org')
    op.drop_table('ticket', schema='itsm')
    op.drop_table('incident', schema='itsm')
    with op.batch_alter_table('software_coverage', schema='equip') as batch_op:
        batch_op.drop_index(batch_op.f('ix_equip_software_coverage_software_id'))

    op.drop_table('software_coverage', schema='equip')
    with op.batch_alter_table('position_software', schema='equip') as batch_op:
        batch_op.drop_index(batch_op.f('ix_equip_position_software_software_id'))
        batch_op.drop_index(batch_op.f('ix_equip_position_software_position_id'))

    op.drop_table('position_software', schema='equip')
    with op.batch_alter_table('position_hardware', schema='equip') as batch_op:
        batch_op.drop_index(batch_op.f('ix_equip_position_hardware_position_id'))
        batch_op.drop_index(batch_op.f('ix_equip_position_hardware_hardware_type_id'))

    op.drop_table('position_hardware', schema='equip')
    with op.batch_alter_table('requirement_history', schema='budget') as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_requirement_history_position_id'))

    op.drop_table('requirement_history', schema='budget')
    with op.batch_alter_table('authorized_count_history', schema='budget') as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_authorized_count_history_position_id'))

    op.drop_table('authorized_count_history', schema='budget')
    with op.batch_alter_table('position', schema='org') as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_position_position_code'))
        batch_op.drop_index(batch_op.f('ix_org_position_division_id'))

    op.drop_table('position', schema='org')
    op.drop_table('change_request', schema='itsm')
    with op.batch_alter_table('software_cost_history', schema='budget') as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_software_cost_history_software_id'))

    op.drop_table('software_cost_history', schema='budget')
    with op.batch_alter_table('hardware_type_cost_history', schema='budget') as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_hardware_type_cost_history_hardware_type_id'))

    op.drop_table('hardware_type_cost_history', schema='budget')
    op.drop_table('cost_snapshot', schema='budget')
    with op.batch_alter_table('user_scope', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_user_scope_user_id'))

    op.drop_table('user_scope', schema='auth')
    op.drop_table('hr_sync_log', schema='audit')
    op.drop_table('audit_log', schema='audit')
    with op.batch_alter_table('asset', schema='asset') as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_asset_manufacturer_id'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_location_id'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_hardware_type_id'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_condition_id'))

    op.drop_table('asset', schema='asset')
    with op.batch_alter_table('division', schema='org') as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_division_division_code'))
        batch_op.drop_index(batch_op.f('ix_org_division_department_id'))

    op.drop_table('division', schema='org')
    with op.batch_alter_table('software', schema='equip') as batch_op:
        batch_op.drop_index(batch_op.f('ix_equip_software_software_type_id'))
        batch_op.drop_index(batch_op.f('ix_equip_software_software_family_id'))

    op.drop_table('software', schema='equip')
    op.drop_table('user', schema='auth')
    op.drop_table('role_permission', schema='auth')
    with op.batch_alter_table('location', schema='asset') as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_location_parent_location_id'))
        batch_op.drop_index(batch_op.f('ix_asset_location_location_type_id'))

    op.drop_table('location', schema='asset')
    with op.batch_alter_table('department', schema='org') as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_department_department_code'))

    op.drop_table('department', schema='org')
    op.drop_table('status', schema='itsm')
    op.drop_table('severity', schema='itsm')
    op.drop_table('priority', schema='itsm')
    op.drop_table('impact', schema='itsm')
    op.drop_table('category', schema='itsm')
    op.drop_table('software_type', schema='equip')
    op.drop_table('software_family', schema='equip')
    op.drop_table('hardware_type', schema='equip')
    op.drop_table('role', schema='auth')
    op.drop_table('permission', schema='auth')
    op.drop_table('operating_system', schema='asset')
    op.drop_table('manufacturer', schema='asset')
    op.drop_table('location_type', schema='asset')
    op.drop_table('condition', schema='asset')
    # ### end Alembic commands ###
